// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Force check for Database URL
const dbUrl = process.env.DATABASE_URL || process.env.NEXT_PUBLIC_DATABASE_URL || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Is line ko humne "!" ke saath mazeed secure kar diya hai
    url: dbUrl!, 
  },
});